language: python

os:
  - linux
  - osx
  - windows

python:
  - "2.7"
  - "3.4"
  - "nightly"

# command to install dependencies
install:
  - "pip install pytest numpy"

# command to run tests
script: pytest -v
